.. produced from googlesheet via scripts/update-schedule.py - edits will be lost
.. role:: rm-past
.. role:: rm-current
.. role:: rm-next
.. role:: rm-future

.. csv-table:: Schedule
   :header: "Event", "Latest", "Long-Term Repo", "Freeze", "Date", "Week #", "Weeks"
   :widths: 9, 9, 9, 9, 9, 4, 4
   :name: roadmap

   ":rm-past:`LTR/PR`",":rm-past:`3.16.0`",":rm-past:`3.10.11`",,":rm-past:`2020-10-23`",":rm-past:`43`",":rm-past:`4`"
   ":rm-past:`PR`",":rm-past:`3.16.1`",":rm-past:`3.10.12`",,":rm-past:`2020-11-20`",":rm-past:`47`",":rm-past:`4`"
   ":rm-past:`PR`",":rm-past:`3.16.2`",":rm-past:`3.10.13`",,":rm-past:`2020-12-21`",":rm-past:`52`",":rm-past:`4`"
   ":rm-past:`PR/FF`",":rm-past:`3.16.3`",":rm-past:`3.10.14`",":rm-past:`3.17`",":rm-past:`2021-01-15`",":rm-past:`3`",":rm-past:`5`"
   ":rm-past:`LR/PR`",":rm-past:`3.18.0`",":rm-past:`3.16.4`",,":rm-past:`2021-02-19`",":rm-past:`8`",":rm-past:`4`"
   ":rm-past:`PR`",":rm-past:`3.18.1`",":rm-past:`3.16.5`",,":rm-past:`2021-03-19`",":rm-past:`12`",":rm-past:`4`"
   ":rm-past:`PR`",":rm-past:`3.18.2`",":rm-past:`3.16.6`",,":rm-past:`2021-04-16`",":rm-past:`16`",":rm-past:`4`"
   ":rm-past:`PR/FF`",":rm-past:`3.18.3`",":rm-past:`3.16.7`",":rm-past:`3.19`",":rm-past:`2021-05-14`",":rm-past:`20`",":rm-past:`5`"
   ":rm-past:`LR/PR`",":rm-past:`3.20.0`",":rm-past:`3.16.8`",,":rm-past:`2021-06-18`",":rm-past:`25`",":rm-past:`4`"
   ":rm-past:`PR`",":rm-past:`3.20.1`",":rm-past:`3.16.9`",,":rm-past:`2021-07-19`",":rm-past:`30`",":rm-past:`4`"
   ":rm-past:`PR`",":rm-past:`3.20.2`",":rm-past:`3.16.10`",,":rm-past:`2021-08-13`",":rm-past:`33`",":rm-past:`4`"
   ":rm-past:`PR/FF`",":rm-past:`3.20.3`",":rm-past:`3.16.11`",":rm-past:`3.21`",":rm-past:`2021-09-10`",":rm-past:`37`",":rm-past:`6`"
   ":rm-current:`LTR/PR`",":rm-current:`3.22.0`",":rm-current:`3.16.12`",,":rm-current:`2021-10-22`",":rm-current:`43`",":rm-current:`2`"
   ":rm-next:`EPR`",,":rm-next:`3.16.13`",,":rm-next:`2021-11-05`",":rm-next:`45`",":rm-next:`2`"
   ":rm-future:`PR`",":rm-future:`3.22.1`",":rm-future:`3.16.14`",,":rm-future:`2021-11-19`",":rm-future:`47`",":rm-future:`4`"
   ":rm-future:`PR`",":rm-future:`3.22.2`",":rm-future:`3.16.15`",,":rm-future:`2021-12-17`",":rm-future:`51`",":rm-future:`4`"
   ":rm-future:`PR/FF`",":rm-future:`3.22.3`",":rm-future:`3.16.16`",":rm-future:`3.23`",":rm-future:`2022-01-14`",":rm-future:`3`",":rm-future:`5`"
   ":rm-future:`LR/PR`",":rm-future:`3.24.0`",":rm-future:`3.22.4`",,":rm-future:`2022-02-18`",":rm-future:`8`",":rm-future:`4`"
   ":rm-future:`PR`",":rm-future:`3.24.1`",":rm-future:`3.22.5`",,":rm-future:`2022-03-18`",":rm-future:`12`",":rm-future:`4`"
   ":rm-future:`PR`",":rm-future:`3.24.2`",":rm-future:`3.22.6`",,":rm-future:`2022-04-15`",":rm-future:`16`",":rm-future:`4`"
   ":rm-future:`PR/FF`",":rm-future:`3.24.3`",":rm-future:`3.22.7`",":rm-future:`3.25`",":rm-future:`2022-05-13`",":rm-future:`20`",":rm-future:`5`"
   ":rm-future:`LR/PR`",":rm-future:`3.26.0`",":rm-future:`3.22.8`",,":rm-future:`2022-06-17`",":rm-future:`25`",":rm-future:`4`"
   ":rm-future:`PR`",":rm-future:`3.26.1`",":rm-future:`3.22.9`",,":rm-future:`2022-07-15`",":rm-future:`29`",":rm-future:`4`"
   ":rm-future:`PR`",":rm-future:`3.26.2`",":rm-future:`3.22.10`",,":rm-future:`2022-08-12`",":rm-future:`33`",":rm-future:`4`"
   ":rm-future:`PR/FF`",":rm-future:`3.26.3`",":rm-future:`3.22.11`",":rm-future:`3.27`",":rm-future:`2022-09-09`",":rm-future:`37`",":rm-future:`6`"
   ":rm-future:`LTR/PR`",":rm-future:`3.28.0`",":rm-future:`3.22.12`",,":rm-future:`2022-10-21`",":rm-future:`43`",":rm-future:`4`"
   ":rm-future:`PR`",":rm-future:`3.28.1`",":rm-future:`3.22.13`",,":rm-future:`2022-11-18`",":rm-future:`47`",":rm-future:`4`"
   ":rm-future:`PR`",":rm-future:`3.28.2`",":rm-future:`3.22.14`",,":rm-future:`2022-12-16`",":rm-future:`51`",":rm-future:`4`"
   ":rm-future:`PR/FF`",":rm-future:`3.28.3`",":rm-future:`3.22.15`",":rm-future:`3.29`",":rm-future:`2023-01-13`",":rm-future:`3`",":rm-future:`5`"

