# -*- coding: utf-8 -*-
#
# QGIS Website documentation build configuration file, created by
# sphinx-quickstart on Fri Aug 23 10:59:00 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

import sphinx.environment
from docutils.utils import get_source_line
from datetime import datetime

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('.'))

# IF THERE IS A docs.conf.py available import it FIRST
# so we will be taking the config for docs first, and after override
# those with ours
# CEVEAT: conflicting vars??
try:
    from docs_conf import *  # NOQA
except ImportError:
    print("docs_conf.py not available, building website without documentation part")


# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.ifconfig',
    'sphinx.ext.extlinks',
#    'sphinxcontrib.images',
    ]

images_config = {
    'override_image_directive':False
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['../themes/qgis-theme']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'site/index'

# General information about the project.
project = u'QGIS'
copyright = u'{0}, QGIS Contributors'.format(datetime.now().year)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.

exec(open("schedule.py").read())

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['../output', "../i18n", "../resources", "../scripts", "../ext", "../virtualenv"]

# The reST default role (used for this markup: `text`) to use for all documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "basic"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = ""

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '../resources/en/common/logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['../themes/qgis-theme/static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%H:%M %b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    'site/index': [],
    'site/**': ['myglobaltoc.html'],
    # 'site/about/**': ['myglobaltoc.html'],
    # 'site/about/index': [],
    # 'site/forusers/**': ['myglobaltoc.html'],
    # 'site/forusers/index': [],
    # 'site/forusers/download': [],
    # 'site/getinvolved/**': ['myglobaltoc.html'],
    # 'site/getinvolved/index': [],
    # 'site/getinvolved/donations': [],
    'docs/**': ['myglobaltoc.html'],
    'docs/index': [],
}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'QGISWebsitedoc'

# if we have a conf.py from the QGIS-Documentation, most parameters can be
# overidden, but we concat the rst_prolog and rst_epilig, to
# docs_rst_prolog = ""
# if "rst_prolog" in locals():
#     docs_rst_prolog = rst_prolog
# rst_prolog = docs_rst_prolog + """
# .. role:: disclaimer
# .. |updatedisclaimer| replace:: :disclaimer:`DISCLAIMER: This section of the user guide has not yet been updated for QGIS 2.0`
# """
#
docs_rst_epilog = ""
if "rst_epilog" in locals():
    docs_rst_epilog = rst_epilog  # NOQA

rst_epilog = docs_rst_epilog + """
.. |checkbox| image:: /static/site/common/checkbox.png
.. |checkbox_unchecked| image:: /static/site/common/checkbox_unchecked.png
.. |QG| replace:: QGIS
.. |qg| replace:: QGIS
.. |yeartag| date:: %%Y
.. |devcite| raw:: html

     <a href="https://docs.qgis.org/%s/en/docs/developers_guide/index.html"> https://docs.qgis.org/%s/en/docs/developers_guide/index.html</a>

.. |userguidecite| raw:: html

     <a href="https://docs.qgis.org/%s/en/docs/user_manual/index.html"> https://docs.qgis.org/%s/en/docs/user_manual/index.html</a>

.. |servercite| raw:: html

     <a href="https://docs.qgis.org/%s/en/docs/server_manual/index.html"> https://docs.qgis.org/%s/en/docs/server_manual/index.html</a>

.. |apicite| raw:: html

     <a href="https://qgis.org/pyqgis/%s/index.html"> https://qgis.org/pyqgis/%s/index.html</a>

"""% (ltrversion, ltrversion, ltrversion, ltrversion,ltrversion, ltrversion, ltrversion, ltrversion)

# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
    ('index', 'QGISWebsite.tex', u'QGIS Website Documentation',
     u'QGIS Contributors', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'qgiswebsite', u'QGIS Website Documentation',
     [u'QGIS Contributors'], 1)
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    ('index', 'QGISWebsite', u'QGIS Website Documentation',
     u'QGIS Contributors', 'QGISWebsite', 'One line description of project.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

locale_dirs = ['../i18n/']
gettext_compact = False


def setup(app):
    app.add_config_value('codename', None, 'env')
    app.add_config_value('releasedate', None, 'env')
    app.add_config_value('releasenote', None, 'env')
    app.add_config_value('ltrversion', None, 'env')
    app.add_config_value('ltrrelease', None, 'env')
    app.add_config_value('ltrcodename', None, 'env')
    app.add_config_value('ltrnote', None, 'env')
    app.add_config_value('devversion', None, 'env')
    app.add_config_value('nextfreezedate', None, 'env')
    app.add_config_value('nextreleasedate', None, 'env')
    app.add_config_value('nextpointreleasedate', None, 'env')
    app.add_config_value('binary', None, 'env')
    app.add_config_value('ltrbinary', None, 'env')
    app.add_config_value('infeaturefreeze', None, 'env')
    app.add_config_value('stripeform_url', None, 'env')


context = {
    'codename': codename,
    'releasedate': releasedate,
    'releasenote': releasenote,
    'ltrversion': ltrversion,
    'ltrrelease': ltrrelease,
    'ltrcodename': ltrcodename,
    'ltrnote': ltrnote,
    'devversion': devversion,
    'nextversion': nextversion,
    'nextfreezedate': nextfreezedate,
    'nextreleasedate': nextreleasedate,
    'nextpointreleasedate': nextpointreleasedate,
    'binary': binary,
    'ltrbinary': ltrbinary,
    'infeaturefreeze': infeaturefreeze,
    'stripeformurl': '/stripe/form'
}

rst_epilog += "\n".join(map(lambda x: ".. |%s| replace:: %s" % (x, context[x]), context.keys()))

extlinks = {'windows_sha256': (f"https://qgis.org/downloads/QGIS-OSGeo4W-{version}-{binary}.sha256sum%s",
                      'SHA256 %s'),
            'windows_ltr_sha256': (f"https://qgis.org/downloads/QGIS-OSGeo4W-{ltrrelease}-{ltrbinary}.sha256sum%s",
                      'SHA256 %s')
}

if 'html_context' in globals():
    html_context.update(context)  # NOQA
else:
    html_context = context

def _warn_node(self, msg, node, **kwargs):
    if 'nonlocal image URI found' not in msg:
        self._warnfunc(msg, '%s:%s' % get_source_line(node))

sphinx.environment.BuildEnvironment.warn_node = _warn_node
